# TTS Provider Configurations
# Each provider has its own section with all necessary parameters

providers:
  # Local TTS Options
  coqui:
    name: "Coqui TTS"
    type: "local"
    models:
      fast:
        model_name: "tts_models/en/ljspeech/tacotron2-DDC_ph"
        description: "Fast, decent quality"
        speed: "fast"
        quality: "medium"

      high_quality:
        model_name: "tts_models/en/ljspeech/glow-tts"
        description: "Higher quality, slower"
        speed: "medium"
        quality: "high"

      xtts:
        model_name: "tts_models/multilingual/multi-dataset/xtts_v2"
        description: "Highest quality, supports voice cloning"
        speed: "slow"
        quality: "very_high"
        supports_voice_cloning: true

    default_model: "fast"
    output_format: "wav"
    sample_rate: 22050

  bark:
    name: "Bark"
    type: "local"
    voice_presets:
      - "v2/en_speaker_0" # Male
      - "v2/en_speaker_1" # Male
      - "v2/en_speaker_2" # Male
      - "v2/en_speaker_3" # Male
      - "v2/en_speaker_4" # Male
      - "v2/en_speaker_5" # Male
      - "v2/en_speaker_6" # Female
      - "v2/en_speaker_7" # Female
      - "v2/en_speaker_8" # Female
      - "v2/en_speaker_9" # Female

    default_voice: "v2/en_speaker_6"
    output_format: "wav"
    sample_rate: 24000
    supports_emotions: true

  edge_tts:
    name: "Microsoft Edge TTS"
    type: "local_api" # Uses Microsoft's servers but free
    voices:
      male:
        - "en-US-BrianNeural"
        - "en-US-ChristopherNeural"
        - "en-US-EricNeural"
        - "en-US-GuyNeural"
        - "en-US-RogerNeural"

      female:
        - "en-US-AriaNeural"
        - "en-US-JennyNeural"
        - "en-US-MichelleNeural"
        - "en-US-MonicaNeural"
        - "en-US-SaraNeural"

    default_voice: "en-US-AriaNeural"
    output_format: "mp3"
    rate: "+0%" # Speech rate adjustment
    pitch: "+0Hz" # Pitch adjustment

  # API-based Options
  openai:
    name: "OpenAI TTS"
    type: "api"
    api_key_env: "OPENAI_API_KEY" # Environment variable name
    models:
      - "tts-1" # Standard quality, faster
      - "tts-1-hd" # HD quality, slower

    voices:
      - "alloy" # Neutral
      - "echo" # Male
      - "fable" # British accent
      - "onyx" # Deep male
      - "nova" # Female (good for longer content)
      - "shimmer" # Female

    default_model: "tts-1-hd"
    default_voice: "nova"
    output_format: "mp3"
    max_chars_per_request: 4096

  elevenlabs:
    name: "ElevenLabs"
    type: "api"
    api_key_env: "ELEVENLABS_API_KEY"
    base_url: "https://api.elevenlabs.io/v1"

    # Note: Voice IDs need to be obtained from ElevenLabs dashboard
    # These are example voice IDs - users need to replace with their own
    voices:
      rachel: "21m00Tcm4TlvDq8ikWAM" # Female, American
      drew: "29vD33N1CtxCmqQRPOHJ" # Male, American
      clyde: "2EiwWnXFnvU5JabPnv8n" # Male, American

    default_voice: "rachel"
    model: "eleven_multilingual_v2"

    voice_settings:
      stability: 0.5
      similarity_boost: 0.5
      style: 0.0
      use_speaker_boost: true

    output_format: "mp3"
    max_chars_per_request: 5000

  google_cloud:
    name: "Google Cloud TTS"
    type: "api"
    credentials_path_env: "GOOGLE_APPLICATION_CREDENTIALS"

    voices:
      standard:
        - "en-US-Standard-A" # Female
        - "en-US-Standard-B" # Male
        - "en-US-Standard-C" # Female
        - "en-US-Standard-D" # Male

      wavenet:
        - "en-US-Wavenet-A" # Female, higher quality
        - "en-US-Wavenet-B" # Male, higher quality
        - "en-US-Wavenet-C" # Female, higher quality
        - "en-US-Wavenet-D" # Male, higher quality

      neural2:
        - "en-US-Neural2-A" # Female, highest quality
        - "en-US-Neural2-C" # Female, highest quality
        - "en-US-Neural2-D" # Male, highest quality
        - "en-US-Neural2-F" # Female, highest quality

    default_voice: "en-US-Neural2-F"
    language_code: "en-US"
    output_format: "mp3"

# Installation requirements for each provider
installation:
  coqui:
    pip: ["TTS"]
    notes: "May require additional system dependencies"

  bark:
    pip: ["git+https://github.com/suno-ai/bark.git", "scipy"]
    notes: "Requires significant disk space for models"

  edge_tts:
    pip: ["edge-tts"]
    notes: "No additional setup required"

  openai:
    pip: ["openai"]
    env_vars: ["OPENAI_API_KEY"]

  elevenlabs:
    pip: ["requests"]
    env_vars: ["ELEVENLABS_API_KEY"]

  google_cloud:
    pip: ["google-cloud-texttospeech"]
    env_vars: ["GOOGLE_APPLICATION_CREDENTIALS"]
